name: lean-reinforcement
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - cuda-toolkit
  - numpy
  - matplotlib
  - jupyter
  - ipykernel
  - pytorch
  - loguru
  - networkx
  - lxml
  - pygithub
  - git-lfs
  - pip:
    - lean-dojo
    - wandb
    - tqdm
    - deepspeed
    - pytorch-lightning[extra]
    - transformers
    - openai
    - rank_bm25
    - vllm
    - -e ReProver/
    - pre-commit
    - gymnasium
