_wandb:
    value:
        cli_version: 0.22.3
        e:
            8kglaus51hbc6s8oudb0du8lpiwr5lk5:
                args:
                    - --data-type
                    - novel_premises
                    - --num-epochs
                    - "10"
                    - --num-theorems
                    - "100"
                    - --num-iterations
                    - "200"
                    - --max-steps
                    - "30"
                    - --mcts-type
                    - guided_rollout
                    - --train-epochs
                    - "1"
                    - --train-value-head
                    - --use-final-reward
                    - --save-training-data
                    - --save-checkpoints
                    - --use-wandb
                cpu_count: 72
                cpu_count_logical: 72
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "270185512960"
                        used: "5201559552"
                email: gerbennkoopman@gmail.com
                executable: /home/gkoopman/.conda/envs/lean-reinforcement/bin/python3
                git:
                    commit: 7a20208abede1b2a1d1f0c8e0270950136d436ad
                    remote: git@github.com:GerbenKoopman/LeanReinforcement.git
                gpu: NVIDIA A100-SXM4-40GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-8037c87c-6993-ae5a-7ffb-fc55f37836d3
                host: gcn34.local.snellius.surf.nl
                memory:
                    total: "540635000832"
                os: Linux-5.14.0-427.92.1.el9_4.x86_64-x86_64-with-glibc2.34
                program: -m src.training.train
                python: CPython 3.10.19
                root: /gpfs/home1/gkoopman/lean_reinforcement
                slurm:
                    cluster_name: snellius
                    conf: /var/spool/slurm/slurmd/conf-cache/slurm.conf
                    cpu_bind: quiet,mask_cpu:0x00003FFFF000000000
                    cpu_bind_list: "0x00003FFFF000000000"
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "18"
                    cpus_per_task: "18"
                    distribution: cyclic
                    eclibr: "0"
                    ecplug: "1"
                    erlast: srun
                    ersbac: "1"
                    ersrun: "1"
                    export_env: ALL
                    get_user_env: "1"
                    gpus: "1"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: gisr101840
                    job_cpus_per_node: "18"
                    job_end_time: "1763918814"
                    job_gid: "73552"
                    job_gpus: "2"
                    job_id: "16868760"
                    job_name: training
                    job_nodelist: gcn34
                    job_num_nodes: "1"
                    job_partition: gpu_a100
                    job_qos: normal
                    job_start_time: "1763854013"
                    job_uid: "74091"
                    job_user: gkoopman
                    jobid: "16868760"
                    launch_node_ipaddr: 172.18.62.34
                    localid: "0"
                    mpi_type: pmi2
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: gcn34
                    nprocs: "1"
                    ntasks: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    srun_comm_host: 172.18.62.34
                    srun_comm_port: "37511"
                    step_gpus: "2"
                    step_gres: gres/cpu:0
                    step_id: "0"
                    step_launcher_port: "37511"
                    step_nodelist: gcn34
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_resv_ports: 17635-17636
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /gpfs/home1/gkoopman/lean_reinforcement/job_files
                    submit_host: int4.local.snellius.surf.nl
                    task_pid: "2709433"
                    tasks_per_node: "1"
                    topology_addr: root.ibsw4.gcn34
                    topology_addr_pattern: switch.switch.node
                    tres_per_task: cpu=18
                    umask: "0027"
                startedAt: "2025-11-22T23:27:25.165545Z"
                writerId: 8kglaus51hbc6s8oudb0du8lpiwr5lk5
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 9
                - 11
                - 30
                - 41
                - 49
                - 103
            "2":
                - 1
                - 9
                - 11
                - 30
                - 41
                - 49
                - 103
            "3":
                - 16
            "4": 3.10.19
            "5": 0.22.3
            "6": 4.57.1
            "12": 0.22.3
            "13": linux-x86_64
checkpoint_dir:
    value: null
data_type:
    value: novel_premises
max_steps:
    value: 30
mcts_type:
    value: guided_rollout
num_epochs:
    value: 10
num_iterations:
    value: 200
num_theorems:
    value: 100
resume:
    value: false
save_checkpoints:
    value: true
save_training_data:
    value: true
train_epochs:
    value: 1
train_value_head:
    value: true
use_final_reward:
    value: true
use_wandb:
    value: true
