_wandb:
    value:
        cli_version: 0.23.1
        e:
            ls14699ae84kzpnzlsy9ow0utwtl5c43:
                args:
                    - --data-type
                    - novel_premises
                    - --indexed-corpus-path
                    - /gpfs/scratch1/shared/lean-reinforcement/indexed_corpus/indexed_corpus.pkl
                    - --num-epochs
                    - "30"
                    - --num-theorems
                    - "128"
                    - --num-iterations
                    - "1000"
                    - --max-steps
                    - "30"
                    - --batch-size
                    - "8"
                    - --num-tactics-to-expand
                    - "16"
                    - --num-workers
                    - "8"
                    - --mcts-type
                    - guided_rollout
                    - --train-epochs
                    - "1"
                    - --train-value-head
                    - --use-final-reward
                    - --save-training-data
                    - --save-checkpoints
                    - --resume
                    - --use-wandb
                cpu_count: 72
                cpu_count_logical: 72
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "270185500672"
                        used: "5181911040"
                email: gerbennkoopman@gmail.com
                executable: /home/gkoopman/.conda/envs/lean-reinforcement/bin/python3
                git:
                    commit: e064cf26f7030e6befcdc33e8529b7596224e7a2
                    remote: git@github.com:GerbenKoopman/LeanReinforcement.git
                gpu: NVIDIA A100-SXM4-40GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-298979f0-6d3d-0977-9c83-1737c2ba55dc
                host: gcn33.local.snellius.surf.nl
                memory:
                    total: "540634976256"
                os: Linux-5.14.0-427.92.1.el9_4.x86_64-x86_64-with-glibc2.34
                program: -m lean_reinforcement.training.train
                python: CPython 3.10.19
                root: /gpfs/home1/gkoopman/lean_reinforcement
                slurm:
                    cluster_name: snellius
                    conf: /var/spool/slurm/slurmd/conf-cache/slurm.conf
                    cpu_bind: quiet,mask_cpu:0x00000000000003FFFF
                    cpu_bind_list: "0x00000000000003FFFF"
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "18"
                    cpus_per_task: "18"
                    distribution: cyclic
                    eclibr: "0"
                    ecplug: "1"
                    erlast: srun
                    ersbac: "1"
                    ersrun: "1"
                    export_env: ALL
                    get_user_env: "1"
                    gpus: "1"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: gisr101840
                    job_cpus_per_node: "18"
                    job_end_time: "1767357794"
                    job_gid: "73552"
                    job_gpus: "0"
                    job_id: "17997915"
                    job_name: guided_rollout_training
                    job_nodelist: gcn33
                    job_num_nodes: "1"
                    job_partition: gpu_a100
                    job_qos: normal
                    job_start_time: "1767184994"
                    job_uid: "74091"
                    job_user: gkoopman
                    jobid: "17997915"
                    launch_node_ipaddr: 172.18.62.33
                    localid: "0"
                    mpi_type: pmi2
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: gcn33
                    nprocs: "1"
                    ntasks: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    srun_comm_host: 172.18.62.33
                    srun_comm_port: "37965"
                    step_gpus: "0"
                    step_gres: gres/cpu:0
                    step_id: "0"
                    step_launcher_port: "37965"
                    step_nodelist: gcn33
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_resv_ports: 12915-12916
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /gpfs/home1/gkoopman/lean_reinforcement/job_files
                    submit_host: int4.local.snellius.surf.nl
                    task_pid: "2484325"
                    tasks_per_node: "1"
                    topology_addr: root.ibsw4.gcn33
                    topology_addr_pattern: switch.switch.node
                    tres_per_task: cpu=18
                    umask: "0027"
                startedAt: "2025-12-31T12:43:45.159680Z"
                writerId: ls14699ae84kzpnzlsy9ow0utwtl5c43
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 9
                - 11
                - 30
                - 41
                - 49
                - 103
            "2":
                - 1
                - 9
                - 11
                - 30
                - 41
                - 49
                - 103
            "3":
                - 16
            "4": 3.10.19
            "5": 0.23.1
            "6": 4.57.3
            "12": 0.23.1
            "13": linux-x86_64
batch_size:
    value: 8
checkpoint_dir:
    value: null
data_type:
    value: novel_premises
env_timeout:
    value: 100
indexed_corpus_path:
    value: /gpfs/scratch1/shared/lean-reinforcement/indexed_corpus/indexed_corpus.pkl
max_rollout_depth:
    value: 30
max_steps:
    value: 30
max_time:
    value: 1200
mcts_type:
    value: guided_rollout
model_name:
    value: kaiyuy/leandojo-lean4-tacgen-byt5-small
num_epochs:
    value: 30
num_iterations:
    value: 1000
num_tactics_to_expand:
    value: 16
num_theorems:
    value: 128
num_workers:
    value: 8
resume:
    value: true
save_checkpoints:
    value: true
save_training_data:
    value: true
train_epochs:
    value: 1
train_value_head:
    value: true
use_final_reward:
    value: true
use_test_value_head:
    value: false
use_wandb:
    value: true
