_wandb:
    value:
        cli_version: 0.23.1
        e:
            aatc1ubqhfevc8bgh6e7n8isfimmw2aj:
                args:
                    - --data-type
                    - novel_premises
                    - --indexed-corpus-path
                    - /indexed_corpus.pkl
                    - --num-epochs
                    - "128"
                    - --num-theorems
                    - "128"
                    - --num-iterations
                    - "200"
                    - --batch-size
                    - "32"
                    - --num-tactics-to-expand
                    - "16"
                    - --num-workers
                    - "16"
                    - --env-timeout
                    - "600"
                    - --max-time
                    - "120"
                    - --proof-timeout
                    - "1200"
                    - --mcts-type
                    - guided_rollout
                    - --train-epochs
                    - "4"
                    - --train-value-head
                    - --use-final-reward
                    - --save-training-data
                    - --save-checkpoints
                    - --resume
                    - --use-wandb
                cpu_count: 16
                cpu_count_logical: 22
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "262486331392"
                        used: "244524343296"
                email: gerbennkoopman@gmail.com
                executable: /home/gerben-koopman/conda/envs/lean-reinforcement/bin/python3
                git:
                    commit: d5ec9c78601cd7076171061a30b3c2f382b94e59
                    remote: git@github.com:GerbenKoopman/LeanReinforcement.git
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 3072
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-f3fa68b1-e965-9828-36c0-091f9369015a
                host: Laptop-studie-linux
                memory:
                    total: "33237979136"
                os: Linux-6.14.0-37-generic-x86_64-with-glibc2.39
                program: -m lean_reinforcement.training.train
                python: CPython 3.10.19
                root: /home/gerben-koopman/projects/study/lean_related/lean_reinforcement
                startedAt: "2026-01-20T19:09:26.511315Z"
                writerId: aatc1ubqhfevc8bgh6e7n8isfimmw2aj
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 9
                - 11
                - 30
                - 41
                - 49
                - 103
            "2":
                - 1
                - 9
                - 11
                - 30
                - 41
                - 49
                - 103
            "3":
                - 16
            "4": 3.10.19
            "5": 0.23.1
            "6": 4.57.3
            "12": 0.23.1
            "13": linux-x86_64
batch_size:
    value: 32
checkpoint_dir:
    value: null
data_type:
    value: novel_premises
env_timeout:
    value: 600
indexed_corpus_path:
    value: /indexed_corpus.pkl
max_rollout_depth:
    value: 30
max_steps:
    value: 10
max_time:
    value: 120
mcts_type:
    value: guided_rollout
model_name:
    value: kaiyuy/leandojo-lean4-tacgen-byt5-small
num_epochs:
    value: 128
num_iterations:
    value: 200
num_tactics_to_expand:
    value: 16
num_theorems:
    value: 128
num_workers:
    value: 16
proof_timeout:
    value: 1200
resume:
    value: true
save_checkpoints:
    value: true
save_training_data:
    value: true
train_epochs:
    value: 4
train_value_head:
    value: true
use_final_reward:
    value: true
use_test_value_head:
    value: false
use_wandb:
    value: true
